Configure repo adapter for prod env
Provide basic configuration, otherwise phoenix complains while compiling

```elixir
    == Compilation error on file lib/ed/repo.ex ==
    ** (ArgumentError) missing :adapter configuration in config :ed, Ed.Repo
        lib/ecto/repo/config.ex:13: Ecto.Repo.Config.parse/2
        lib/ed/repo.ex:2: (module)
        (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```